-- ============================================================================
-- install.sql — stand up a NEW Zuwera database.
--
-- GENERATED. Do not edit by hand: run
--     node scripts/build-install-sql.js <schema-dump.sql>
-- and commit the result. Hand edits are lost on the next regeneration and,
-- worse, make this file disagree with production — which is exactly how the 32
-- root supabase-*.sql files stopped being able to rebuild anything.
--
-- WHAT THIS IS FOR
--   A new project: a licensee, a second store, a restore into a fresh Supabase
--   project. Run this ONCE, in the SQL editor. It is the ONLY thing you run —
--   do not also run migrations/0001, which is for databases that predate the
--   migration system. Everything 0001 creates is already in here.
--
-- WHAT THIS IS NOT FOR
--   An existing database. To change one, add a file to migrations/ and apply it
--   from Admin → APIs → Database migrations. The guard below refuses to run if
--   any core table already holds rows, so a paste into the wrong SQL editor
--   fails loudly instead of succeeding catastrophically.
--
-- WHY A SNAPSHOT RATHER THAN REPLAYING THE MIGRATIONS
--   The migration chain only ever ran on top of a schema that already existed.
--   Replaying it against an empty database is a sequence nobody has executed and
--   nothing tests. This file is the finished state, and it ends by recording
--   every migration through HEAD as applied — so the runner has nothing pending
--   and never replays history it was not written for.
--
-- Generated 2026-08-14 from a production schema dump.
-- ============================================================================

do $$
declare
  n bigint;
begin
  if to_regclass('public.orders') is not null then
    execute 'select count(*) from public.orders' into n;
    if n > 0 then
      raise exception using
        message = 'REFUSING TO RUN: public.orders already contains ' || n || ' row(s).',
        hint    = 'install.sql is for a NEW project. To change an existing database, add a file to migrations/ and apply it from Admin -> APIs -> Database migrations.';
    end if;
  end if;

  if to_regclass('public.products') is not null then
    execute 'select count(*) from public.products' into n;
    if n > 0 then
      raise exception using
        message = 'REFUSING TO RUN: public.products already contains ' || n || ' row(s).',
        hint    = 'install.sql is for a NEW project. Use migrations/ for changes to an existing database.';
    end if;
  end if;
end
$$;

--
-- Zuwera public schema. Generated by scripts/dump-schema.js on 2026-08-14.
--

-- extensions
create extension if not exists "pg_cron" with schema "pg_catalog";
create extension if not exists "pg_stat_statements" with schema "extensions";
create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "supabase_vault" with schema "vault";
create extension if not exists "uuid-ossp" with schema "extensions";

-- sequences
create sequence if not exists public."error_log_id_seq";
create sequence if not exists public."zw_insert_throttle_id_seq";

-- tables
create table if not exists public."abandoned_carts" (
  "id" uuid default gen_random_uuid() not null,
  "email" text not null,
  "cart" jsonb default '[]'::jsonb not null,
  "subtotal_cents" integer default 0,
  "item_count" integer default 0,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "recovered_at" timestamp with time zone,
  "emailed_at" timestamp with time zone
);
create table if not exists public."admin_audit_log" (
  "id" uuid default gen_random_uuid() not null,
  "created_at" timestamp with time zone default now() not null,
  "admin_user_id" uuid,
  "admin_email" text,
  "action" text not null,
  "resource_type" text not null,
  "resource_id" text,
  "metadata" jsonb default '{}'::jsonb not null,
  "user_agent" text
);
create table if not exists public."api_key_overrides" (
  "key" text not null,
  "value" text not null,
  "updated_at" timestamp with time zone default now() not null
);
create table if not exists public."api_status_log" (
  "id" bigint default nextval('api_status_log_id_seq'::regclass) not null,
  "service" text not null,
  "ok" boolean not null,
  "configured" boolean,
  "detail" text,
  "checked_at" timestamp with time zone default now() not null
);
create table if not exists public."bundles" (
  "id" uuid default gen_random_uuid() not null,
  "name" text not null,
  "blurb" text,
  "product_ids" jsonb default '[]'::jsonb not null,
  "promo_code" text,
  "active" boolean default true not null,
  "sort_order" integer default 0 not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);
create table if not exists public."color_variants" (
  "id" uuid default gen_random_uuid() not null,
  "product_id" uuid not null,
  "color_name" text not null,
  "hex_color" text not null,
  "rgb_color" text,
  "variant_sku" text,
  "sort_order" integer default 0
);
create table if not exists public."disputes" (
  "id" text not null,
  "charge_id" text,
  "payment_intent" text,
  "order_id" text,
  "amount" integer,
  "currency" text,
  "reason" text,
  "status" text,
  "evidence_due" timestamp with time zone,
  "opened_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "raw" jsonb
);
create table if not exists public."email_log" (
  "id" uuid default gen_random_uuid() not null,
  "type" text not null,
  "recipient" text,
  "subject" text,
  "status" text default 'sent'::text not null,
  "provider" text,
  "meta" jsonb default '{}'::jsonb not null,
  "created_at" timestamp with time zone default now() not null
);
create table if not exists public."error_log" (
  "id" bigint generated always as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "message" text,
  "source" text,
  "url" text,
  "line" integer,
  "col" integer,
  "stack" text,
  "user_agent" text,
  "release" text,
  "extra" jsonb
);
create table if not exists public."favorites" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "product_id" uuid not null,
  "product_name" text,
  "price" text,
  "created_at" timestamp with time zone default now(),
  "product_image" text
);
create table if not exists public."journal_posts" (
  "id" uuid default gen_random_uuid() not null,
  "title" text not null,
  "slug" text not null,
  "excerpt" text,
  "body" text,
  "cover_image" text,
  "status" text default 'draft'::text not null,
  "published_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);
create table if not exists public."loyalty_ledger" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "points" integer not null,
  "reason" text default 'purchase'::text not null,
  "order_id" text,
  "promo_code" text,
  "created_at" timestamp with time zone default now() not null
);
create table if not exists public."newsletter_subscribers" (
  "id" uuid default gen_random_uuid() not null,
  "email" text not null,
  "status" text default 'subscribed'::text not null,
  "source" text,
  "unsub_token" text default encode(gen_random_bytes(16), 'hex'::text) not null,
  "created_at" timestamp with time zone default now() not null,
  "unsubscribed_at" timestamp with time zone
);
create table if not exists public."orders" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid,
  "status" text default 'Confirmed'::text,
  "total_amount" numeric(10,2),
  "created_at" timestamp with time zone default now(),
  "stripe_payment_intent_id" text,
  "email" text,
  "customer_name" text,
  "items" text,
  "subtotal" numeric(10,2),
  "shipping" numeric(10,2),
  "tax" numeric(10,2) default 0,
  "total" numeric(10,2),
  "ship_line1" text,
  "ship_line2" text,
  "ship_city" text,
  "ship_state" text,
  "ship_zip" text,
  "ship_country" text default 'US'::text,
  "shipping_provider" text,
  "shipping_service" text,
  "tracking_number" text,
  "tracking_url" text,
  "label_url" text,
  "free_shipping" boolean default false,
  "order_number" text,
  "feature_flags" jsonb,
  "delivery_method" text,
  "review_requested_at" timestamp with time zone,
  "tax_engine" text,
  "risk_level" text,
  "risk_score" integer,
  "actual_shipping_cost" numeric(10,2),
  "delivered_at" timestamp with time zone
);
create table if not exists public."processed_events" (
  "event_id" text not null,
  "event_type" text,
  "seen_at" timestamp with time zone default now() not null
);
create table if not exists public."product_images" (
  "id" uuid default gen_random_uuid() not null,
  "product_id" uuid not null,
  "image_url" text not null,
  "sort_order" integer default 0 not null,
  "alt_text" text,
  "created_at" timestamp with time zone default now(),
  "media_type" text default 'image'::text not null,
  "color_variant_id" uuid
);
create table if not exists public."product_questions" (
  "id" uuid default gen_random_uuid() not null,
  "product_id" uuid,
  "question" text not null,
  "answer" text,
  "asker_name" text,
  "status" text default 'pending'::text not null,
  "created_at" timestamp with time zone default now() not null,
  "answered_at" timestamp with time zone
);
create table if not exists public."product_sizes" (
  "id" uuid default gen_random_uuid() not null,
  "product_id" uuid not null,
  "size" text not null,
  "stock_quantity" integer default 0 not null,
  "created_at" timestamp with time zone default now(),
  "color_name" text,
  "color_hex" text
);
create table if not exists public."products" (
  "id" uuid default gen_random_uuid() not null,
  "sku" text,
  "title" text not null,
  "subtitle" text,
  "gender" text,
  "colorway" text,
  "material_composition" text,
  "msrp" numeric(10,2),
  "current_price" numeric(10,2),
  "member_price" numeric(10,2),
  "model_height" text,
  "model_size_worn" text,
  "fit_type" text,
  "fabric_technology" text,
  "fabric_weight_gsm" numeric,
  "upf_rating" integer,
  "breathability_mvtr" numeric,
  "pom_chest" numeric,
  "pom_waist" numeric,
  "pom_inseam" numeric,
  "pom_hips" numeric,
  "pom_length" numeric,
  "pom_shoulder" numeric,
  "pom_sleeve" numeric,
  "sustainability_tags" text[] default ARRAY[]::text[],
  "certifications" text[] default ARRAY[]::text[],
  "specialty_sizing" text[] default ARRAY[]::text[],
  "country_of_origin" text,
  "care_instructions" text,
  "drop_number" text,
  "status" text default 'Draft'::text,
  "sort_order" integer default 0,
  "low_stock_threshold" integer default 10,
  "image_url" text,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "shipping_weight_lb" numeric(5,2) default NULL::numeric,
  "image_focal_y" integer default 0 not null,
  "category" text,
  "tags" text[] default '{}'::text[],
  "descriptor" text,
  "sports" text[],
  "best_for" text[],
  "tax_category" text
);
create table if not exists public."profiles" (
  "id" uuid not null,
  "email" text,
  "full_name" text,
  "role" text default 'customer'::text not null,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "preferences" jsonb,
  "admin_role" text,
  "admin_permissions" jsonb
);
create table if not exists public."referral_codes" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "code" text not null,
  "created_at" timestamp with time zone default now() not null
);
create table if not exists public."restock_requests" (
  "id" uuid default gen_random_uuid() not null,
  "product_id" uuid not null,
  "size" text not null,
  "color_name" text,
  "email" text not null,
  "created_at" timestamp with time zone default now() not null,
  "notified_at" timestamp with time zone
);
create table if not exists public."return_requests" (
  "id" uuid default gen_random_uuid() not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "user_id" uuid,
  "order_id" text not null,
  "order_label" text,
  "order_total" numeric(10,2),
  "order_status" text,
  "customer_email" text,
  "customer_name" text,
  "resolution" text default 'return'::text not null,
  "status" text default 'requested'::text not null,
  "reason" text default ''::text not null,
  "notes" text default ''::text not null,
  "internal_notes" text default ''::text not null,
  "customer_message" text default ''::text not null,
  "exchange_sku" text default ''::text not null,
  "shipping_address" jsonb,
  "label_url" text,
  "tracking_number" text,
  "tracking_url" text,
  "carrier" text,
  "service" text,
  "label_error" text,
  "label_sent_at" timestamp with time zone,
  "inspection_notes" text default ''::text not null
);
create table if not exists public."reviews" (
  "id" uuid default gen_random_uuid() not null,
  "product_id" uuid not null,
  "user_id" uuid,
  "rating" integer not null,
  "title" text,
  "body" text,
  "nickname" text,
  "reviewer_name" text,
  "verified_purchase" boolean default false,
  "created_at" timestamp with time zone default now(),
  "admin_response" text,
  "fit_rating" integer,
  "comfort_rating" integer,
  "recommend" boolean,
  "photos" jsonb default '[]'::jsonb not null,
  "photos_approved" boolean default false not null
);
create table if not exists public."schema_migrations" (
  "version" text not null,
  "name" text not null,
  "checksum" text not null,
  "applied_at" timestamp with time zone default now() not null,
  "applied_by" text
);
create table if not exists public."site_settings" (
  "key" text not null,
  "value" jsonb not null,
  "updated_at" timestamp with time zone default now()
);
create table if not exists public."size_charts" (
  "id" uuid default gen_random_uuid() not null,
  "category" text not null,
  "size_label" text not null,
  "us_size" text,
  "numeric_size" text,
  "height_in" text,
  "chest_in" text,
  "waist_in" text,
  "hips_in" text,
  "bust_in" text,
  "head_circ_in" text,
  "head_circ_cm" text,
  "band_size" text,
  "cup_size" text,
  "us_mens" text,
  "us_womens" text,
  "us_kids" text,
  "uk" text,
  "eu" text
);
create table if not exists public."tax_exemptions" (
  "id" uuid default gen_random_uuid() not null,
  "email" text,
  "user_id" uuid,
  "states" text[] default '{}'::text[],
  "certificate" text,
  "business_name" text,
  "note" text,
  "expires_at" timestamp with time zone,
  "revoked_at" timestamp with time zone,
  "created_at" timestamp with time zone default now(),
  "created_by" uuid
);
create table if not exists public."tax_shadow_log" (
  "id" bigint default nextval('tax_shadow_log_id_seq'::regclass) not null,
  "created_at" timestamp with time zone default now(),
  "order_number" text,
  "state" text,
  "zip" text,
  "taxable_cents" integer,
  "live_engine" text,
  "live_cents" integer,
  "shadow_engine" text,
  "shadow_cents" integer,
  "delta_cents" integer,
  "shadow_error" text
);
create table if not exists public."waitlist" (
  "id" uuid default gen_random_uuid() not null,
  "email" text not null,
  "source" text,
  "created_at" timestamp with time zone default now()
);
create table if not exists public."webhook_events" (
  "id" uuid default gen_random_uuid() not null,
  "received_at" timestamp with time zone default now() not null,
  "event_type" text,
  "payment_intent" text,
  "customer_email" text,
  "amount_cents" integer,
  "sig_verified" boolean default false not null,
  "error_message" text,
  "raw_status" text
);
create table if not exists public."zw_banned_words" (
  "word" text not null
);
create table if not exists public."zw_insert_throttle" (
  "id" bigint generated always as identity not null,
  "bucket" text not null,
  "ip" text not null,
  "created_at" timestamp with time zone default now() not null
);

-- constraints
alter table public."abandoned_carts" add constraint "abandoned_carts_pkey" PRIMARY KEY (id);
alter table public."admin_audit_log" add constraint "admin_audit_log_pkey" PRIMARY KEY (id);
alter table public."api_key_overrides" add constraint "api_key_overrides_pkey" PRIMARY KEY (key);
alter table public."api_status_log" add constraint "api_status_log_pkey" PRIMARY KEY (id);
alter table public."bundles" add constraint "bundles_pkey" PRIMARY KEY (id);
alter table public."color_variants" add constraint "color_variants_pkey" PRIMARY KEY (id);
alter table public."disputes" add constraint "disputes_pkey" PRIMARY KEY (id);
alter table public."email_log" add constraint "email_log_pkey" PRIMARY KEY (id);
alter table public."error_log" add constraint "error_log_pkey" PRIMARY KEY (id);
alter table public."favorites" add constraint "favorites_pkey" PRIMARY KEY (id);
alter table public."journal_posts" add constraint "journal_posts_pkey" PRIMARY KEY (id);
alter table public."loyalty_ledger" add constraint "loyalty_ledger_pkey" PRIMARY KEY (id);
alter table public."newsletter_subscribers" add constraint "newsletter_subscribers_pkey" PRIMARY KEY (id);
alter table public."orders" add constraint "orders_pkey" PRIMARY KEY (id);
alter table public."processed_events" add constraint "processed_events_pkey" PRIMARY KEY (event_id);
alter table public."product_images" add constraint "product_images_pkey" PRIMARY KEY (id);
alter table public."product_questions" add constraint "product_questions_pkey" PRIMARY KEY (id);
alter table public."product_sizes" add constraint "product_sizes_pkey" PRIMARY KEY (id);
alter table public."products" add constraint "products_pkey" PRIMARY KEY (id);
alter table public."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);
alter table public."referral_codes" add constraint "referral_codes_pkey" PRIMARY KEY (id);
alter table public."restock_requests" add constraint "restock_requests_pkey" PRIMARY KEY (id);
alter table public."return_requests" add constraint "return_requests_pkey" PRIMARY KEY (id);
alter table public."reviews" add constraint "reviews_pkey" PRIMARY KEY (id);
alter table public."schema_migrations" add constraint "schema_migrations_pkey" PRIMARY KEY (version);
alter table public."site_settings" add constraint "site_settings_pkey" PRIMARY KEY (key);
alter table public."size_charts" add constraint "size_charts_pkey" PRIMARY KEY (id);
alter table public."tax_exemptions" add constraint "tax_exemptions_pkey" PRIMARY KEY (id);
alter table public."tax_shadow_log" add constraint "tax_shadow_log_pkey" PRIMARY KEY (id);
alter table public."waitlist" add constraint "waitlist_pkey" PRIMARY KEY (id);
alter table public."webhook_events" add constraint "webhook_events_pkey" PRIMARY KEY (id);
alter table public."zw_banned_words" add constraint "zw_banned_words_pkey" PRIMARY KEY (word);
alter table public."zw_insert_throttle" add constraint "zw_insert_throttle_pkey" PRIMARY KEY (id);
alter table public."favorites" add constraint "favorites_user_id_product_id_key" UNIQUE (user_id, product_id);
alter table public."favorites" add constraint "favorites_user_product_unique" UNIQUE (user_id, product_id);
alter table public."journal_posts" add constraint "journal_posts_slug_key" UNIQUE (slug);
alter table public."products" add constraint "products_sku_key" UNIQUE (sku);
alter table public."referral_codes" add constraint "referral_codes_code_key" UNIQUE (code);
alter table public."referral_codes" add constraint "referral_codes_user_id_key" UNIQUE (user_id);
alter table public."waitlist" add constraint "waitlist_email_source_key" UNIQUE (email, source);
alter table public."email_log" add constraint "email_log_status_check" CHECK ((status = ANY (ARRAY['sent'::text, 'failed'::text])));
alter table public."newsletter_subscribers" add constraint "newsletter_subscribers_status_check" CHECK ((status = ANY (ARRAY['subscribed'::text, 'unsubscribed'::text])));
alter table public."product_images" add constraint "product_images_media_type_check" CHECK ((media_type = ANY (ARRAY['image'::text, 'video'::text])));
alter table public."products" add constraint "products_image_focal_y_check" CHECK (((image_focal_y >= 0) AND (image_focal_y <= 100)));
alter table public."profiles" add constraint "profiles_admin_role_chk" CHECK (((admin_role IS NULL) OR (admin_role = ANY (ARRAY['super_admin'::text, 'manager'::text, 'finance'::text, 'fulfillment'::text, 'content'::text, 'viewer'::text]))));
alter table public."return_requests" add constraint "return_requests_resolution_check" CHECK ((resolution = ANY (ARRAY['return'::text, 'exchange'::text, 'store_credit'::text])));
alter table public."return_requests" add constraint "return_requests_status_check" CHECK ((status = ANY (ARRAY['requested'::text, 'approved'::text, 'label_sent'::text, 'denied'::text, 'exchange_in_progress'::text, 'completed'::text, 'refunded'::text, 'closed'::text])));
alter table public."reviews" add constraint "reviews_comfort_rating_check" CHECK (((comfort_rating >= 1) AND (comfort_rating <= 5)));
alter table public."reviews" add constraint "reviews_fit_rating_check" CHECK (((fit_rating >= 1) AND (fit_rating <= 5)));
alter table public."reviews" add constraint "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5)));
alter table public."admin_audit_log" add constraint "admin_audit_log_admin_user_id_fkey" FOREIGN KEY (admin_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public."color_variants" add constraint "color_variants_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public."favorites" add constraint "favorites_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public."favorites" add constraint "favorites_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."loyalty_ledger" add constraint "loyalty_ledger_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."orders" add constraint "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."product_images" add constraint "product_images_color_variant_id_fkey" FOREIGN KEY (color_variant_id) REFERENCES color_variants(id) ON DELETE SET NULL;
alter table public."product_images" add constraint "product_images_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public."product_questions" add constraint "product_questions_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public."product_sizes" add constraint "product_sizes_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."referral_codes" add constraint "referral_codes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."restock_requests" add constraint "restock_requests_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public."return_requests" add constraint "return_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public."reviews" add constraint "reviews_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public."reviews" add constraint "reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

-- indexes
create index admin_audit_log_created_at_idx ON public.admin_audit_log USING btree (created_at DESC);
create index admin_audit_log_resource_idx ON public.admin_audit_log USING btree (resource_type, resource_id);
create index api_status_log_service_time_idx ON public.api_status_log USING btree (service, checked_at DESC);
create index api_status_log_time_idx ON public.api_status_log USING btree (checked_at);
create index disputes_order_idx ON public.disputes USING btree (order_id);
create index disputes_status_idx ON public.disputes USING btree (status);
create index email_log_created_idx ON public.email_log USING btree (created_at DESC);
create index email_log_type_idx ON public.email_log USING btree (type);
create index error_log_created_at_idx ON public.error_log USING btree (created_at DESC);
create index error_log_source_time_idx ON public.error_log USING btree (source, created_at DESC);
create index idx_admin_audit_log_admin_user_id ON public.admin_audit_log USING btree (admin_user_id);
create index idx_color_variants_product_id ON public.color_variants USING btree (product_id);
create index idx_favorites_product_id ON public.favorites USING btree (product_id);
create index idx_orders_user_id ON public.orders USING btree (user_id);
create index idx_product_images_color ON public.product_images USING btree (color_variant_id);
create index idx_product_images_product_id ON public.product_images USING btree (product_id);
create index idx_product_questions_product ON public.product_questions USING btree (product_id, status);
create index idx_return_requests_user_id ON public.return_requests USING btree (user_id);
create index idx_reviews_product_id ON public.reviews USING btree (product_id);
create index idx_reviews_user_id ON public.reviews USING btree (user_id);
create index loyalty_ledger_user_idx ON public.loyalty_ledger USING btree (user_id, created_at DESC);
create unique index newsletter_subscribers_email_key ON public.newsletter_subscribers USING btree (lower(email));
create index orders_delivered_at_idx ON public.orders USING btree (delivered_at DESC NULLS LAST);
create unique index orders_order_number_key ON public.orders USING btree (order_number) WHERE (order_number IS NOT NULL);
create unique index orders_stripe_pi_id_idx ON public.orders USING btree (stripe_payment_intent_id) WHERE (stripe_payment_intent_id IS NOT NULL);
create index processed_events_seen_at_idx ON public.processed_events USING btree (seen_at);
create unique index product_sizes_product_id_size_color_key ON public.product_sizes USING btree (product_id, size, color_name) WHERE (color_name IS NOT NULL);
create unique index product_sizes_product_id_size_nocolor_key ON public.product_sizes USING btree (product_id, size) WHERE (color_name IS NULL);
create index referral_codes_code_idx ON public.referral_codes USING btree (upper(code));
create index restock_requests_product ON public.restock_requests USING btree (product_id, size);
create unique index restock_requests_unique ON public.restock_requests USING btree (product_id, size, COALESCE(color_name, ''::text), lower(email));
create index tax_exemptions_email_idx ON public.tax_exemptions USING btree (lower(email)) WHERE (email IS NOT NULL);
create index tax_exemptions_user_idx ON public.tax_exemptions USING btree (user_id) WHERE (user_id IS NOT NULL);
create index tax_shadow_log_created_idx ON public.tax_shadow_log USING btree (created_at DESC);
create unique index uniq_abandoned_carts_email ON public.abandoned_carts USING btree (lower(email));
create unique index waitlist_email_unique ON public.waitlist USING btree (lower(email));
create index webhook_events_pi_idx ON public.webhook_events USING btree (payment_intent);
create index webhook_events_received_idx ON public.webhook_events USING btree (received_at DESC);
create index zw_insert_throttle_lookup ON public.zw_insert_throttle USING btree (bucket, ip, created_at);

-- functions
CREATE OR REPLACE FUNCTION public.apply_migration(p_version text, p_name text, p_sql text, p_checksum text, p_actor text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if exists (select 1 from public.schema_migrations where version = p_version) then
    return;                                    -- already applied; do nothing
  end if;

  execute p_sql;

  insert into public.schema_migrations (version, name, checksum, applied_by)
  values (p_version, p_name, p_checksum, p_actor);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.current_user_can_page(p_page text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and (
        -- Super admins hold every page, as they do in resolvePerms().
        admin_role = 'super_admin'
        -- No explicit map: unchanged from before this migration. See the note
        -- above — inferring one from a role preset would duplicate the model.
        or admin_permissions -> 'pages' is null
        -- Explicit map: 'view' and 'edit' both grant read, 'none' and a missing
        -- key do not. Same two levels resolvePerms() treats as access.
        or coalesce(admin_permissions -> 'pages' ->> p_page, '') in ('view', 'edit')
      )
  );
$function$
;

CREATE OR REPLACE FUNCTION public.current_user_is_admin()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.current_user_is_super_admin()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
      AND coalesce(admin_role, 'super_admin') = 'super_admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.decrement_stock(p_product_id uuid, p_size text, p_qty integer, p_color_name text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id      uuid;
  v_changed integer := 0;
BEGIN
  IF p_product_id IS NULL OR p_qty IS NULL OR p_qty <= 0 THEN
    RETURN 0;
  END IF;

  v_id := zw_find_size_row(p_product_id, p_size, p_color_name);

  IF v_id IS NULL THEN
    RAISE WARNING 'decrement_stock: no row for product % size % colour %',
      p_product_id, p_size, coalesce(p_color_name, '(none)');
    RETURN 0;
  END IF;

  UPDATE product_sizes
  SET stock_quantity = GREATEST(0, coalesce(stock_quantity, 0) - p_qty)
  WHERE id = v_id;

  GET DIAGNOSTICS v_changed = ROW_COUNT;
  RETURN v_changed;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_user(target_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
BEGIN
  IF target_user_id IS NULL THEN
    RAISE EXCEPTION 'target_user_id is required';
  END IF;

  IF NOT public.current_user_is_admin() THEN
    RAISE EXCEPTION 'Only admins can delete users';
  END IF;

  IF auth.uid() = target_user_id THEN
    RAISE EXCEPTION 'Admins cannot delete their own account from the admin panel';
  END IF;

  DELETE FROM public.favorites WHERE user_id = target_user_id;
  UPDATE public.reviews SET user_id = NULL WHERE user_id = target_user_id;
  UPDATE public.orders SET user_id = NULL WHERE user_id = target_user_id;
  DELETE FROM public.profiles WHERE id = target_user_id;
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.guard_admin_privilege_columns()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.admin_role IS NOT DISTINCT FROM OLD.admin_role
     AND NEW.admin_permissions IS NOT DISTINCT FROM OLD.admin_permissions
     AND NEW.role IS NOT DISTINCT FROM OLD.role THEN
    RETURN NEW;                       -- nothing privilege-bearing changed
  END IF;

  -- Server-side writes. auth.uid() is NULL for the service role, which is how
  -- set-admin-role.js writes — and it has already checked RBAC and the limits.
  -- Without this the endpoint we want people using would be the one thing that
  -- stopped working.
  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  IF NOT public.current_user_is_super_admin() THEN
    RAISE EXCEPTION 'Only a super admin can change roles or permissions (use the Users page)';
  END IF;

  -- Even a super admin, on their own row. Not because they lack the authority
  -- — they can grant it to somebody who grants it back — but because every
  -- self-promotion in the log should read as somebody else's decision. It also
  -- means one compromised session cannot quietly widen itself.
  IF auth.uid() = NEW.id THEN
    RAISE EXCEPTION 'You cannot change your own role or permissions';
  END IF;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'full_name', 'customer');
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_authz_settings_key(k text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
AS $function$
  SELECT k IN ('abac_rules', 'refund_audit_log', 'refund_rate_limit');
$function$
;

CREATE OR REPLACE FUNCTION public.is_super_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.admin_role = 'super_admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.prevent_profile_role_self_change()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.uid() = NEW.id
     AND NEW.role IS DISTINCT FROM OLD.role
     AND NOT public.current_user_is_admin() THEN
    RAISE EXCEPTION 'Only admins can change profile roles';
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.prevent_profile_role_self_elevation()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Only intervene when a user is updating their own row
  IF auth.uid() = NEW.id AND OLD.role IS DISTINCT FROM NEW.role THEN
    -- Allow if the caller is already an admin; otherwise revert
    IF NOT current_user_is_admin() THEN
      NEW.role := OLD.role;
    END IF;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.prune_error_log(p_batch integer DEFAULT 2000)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_total integer := 0;
  v_n     integer := 0;
  v_batch integer := greatest(1, least(coalesce(p_batch, 2000), 20000));
begin
  /* A CSP report matters while the violation is live. One that stopped two
     weeks ago is either fixed or nobody cares — and if it is still happening, a
     fresh row is being written right now. */
  delete from error_log
  where ctid in (
    select ctid from error_log
    where source = 'csp' and created_at < now() - interval '14 days'
    limit v_batch
  );
  get diagnostics v_n = row_count;
  v_total := v_total + v_n;

  /* Real errors get a quarter. Long enough to see a pattern, short enough that
     this table cannot become the biggest thing in a 500 MB database. */
  delete from error_log
  where ctid in (
    select ctid from error_log
    where source <> 'csp' and created_at < now() - interval '90 days'
    limit v_batch
  );
  get diagnostics v_n = row_count;
  return v_total + v_n;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.record_api_status(p_rows jsonb)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_count integer := 0;
begin
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    return 0;
  end if;

  insert into api_status_log (service, ok, configured, detail)
  select
    left(r->>'service', 64),
    coalesce((r->>'ok')::boolean, false),
    (r->>'configured')::boolean,
    left(r->>'detail', 500)          -- recognising a repeat, not storing a trace
  from jsonb_array_elements(p_rows) as r
  where coalesce(r->>'service', '') <> '';

  get diagnostics v_count = row_count;

  /* Kept to 30 days, here rather than in a scheduled job, because a job nobody
     runs is how this table becomes the biggest thing in the database. Only
     fires occasionally — a delete on every write is pure overhead once the old
     rows are already gone. */
  if random() < 0.02 then
    delete from api_status_log where checked_at < now() - interval '30 days';
  end if;

  return v_count;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.restock_stock(p_product_id uuid, p_size text, p_qty integer, p_color_name text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id      uuid;
  v_changed integer := 0;
BEGIN
  IF p_product_id IS NULL OR p_qty IS NULL OR p_qty <= 0 THEN
    RETURN 0;
  END IF;

  v_id := zw_find_size_row(p_product_id, p_size, p_color_name);

  IF v_id IS NULL THEN
    RAISE WARNING 'restock_stock: no row for product % size % colour %',
      p_product_id, p_size, coalesce(p_color_name, '(none)');
    RETURN 0;
  END IF;

  -- No upper clamp: stock coming back from a return is a real count, and a
  -- ceiling here would silently swallow it.
  UPDATE product_sizes
  SET stock_quantity = coalesce(stock_quantity, 0) + p_qty
  WHERE id = v_id;

  GET DIAGNOSTICS v_changed = ROW_COUNT;
  RETURN v_changed;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.reviews_guard_photo_approval()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if not public.current_user_is_admin() then
    new.photos_approved := false;
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_return_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.zw_canon_size(p_size text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  SELECT CASE
    WHEN s ~ '^([2-5])x(s|l)$' THEN repeat('x', (substring(s from 1 for 1))::int) || substring(s from 3)
    ELSE s
  END
  FROM (SELECT lower(regexp_replace(coalesce(p_size, ''), '\s', '', 'g')) AS s) t;
$function$
;

CREATE OR REPLACE FUNCTION public.zw_find_size_row(p_product_id uuid, p_size text, p_color_name text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id uuid;
BEGIN
  IF p_product_id IS NULL THEN
    RETURN NULL;
  END IF;

  -- 1) The colour actually named, matched the way the storefront matches it.
  IF p_color_name IS NOT NULL AND btrim(p_color_name) <> '' THEN
    SELECT id INTO v_id
    FROM product_sizes
    WHERE product_id = p_product_id
      AND zw_canon_size(size) = zw_canon_size(p_size)
      AND lower(btrim(coalesce(color_name, ''))) = lower(btrim(p_color_name))
    ORDER BY created_at ASC
    LIMIT 1;
  END IF;

  -- 2) Colour-agnostic rows ONLY. A row with color_name NULL genuinely covers
  --    every colourway. Another COLOUR's row describes a different garment, and
  --    reaching for it is what made a sold colour never go down while an unsold
  --    one drained to zero.
  IF v_id IS NULL THEN
    SELECT id INTO v_id
    FROM product_sizes
    WHERE product_id = p_product_id
      AND zw_canon_size(size) = zw_canon_size(p_size)
      AND color_name IS NULL
    ORDER BY created_at ASC
    LIMIT 1;
  END IF;

  RETURN v_id;   -- NULL means nothing describes this garment. Say so; do not guess.
END;
$function$
;

CREATE OR REPLACE FUNCTION public.zw_rate_limit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_headers json;
  v_ip text;
  v_limit int := tg_argv[0]::int;
  v_window interval := tg_argv[1]::interval;
  v_count int;
begin
  -- Backend (service role) is never throttled.
  if coalesce(current_setting('request.jwt.claims', true)::json->>'role','') = 'service_role' then
    return new;
  end if;

  begin
    v_headers := current_setting('request.headers', true)::json;
  exception when others then
    v_headers := null;
  end;
  v_ip := coalesce(
    v_headers->>'cf-connecting-ip',
    split_part(coalesce(v_headers->>'x-forwarded-for',''), ',', 1),
    ''
  );
  -- No client IP (e.g. SQL console) — don't blind-throttle.
  if v_ip is null or v_ip = '' then
    return new;
  end if;

  select count(*) into v_count
  from public.zw_insert_throttle
  where bucket = tg_table_name and ip = v_ip and created_at > now() - v_window;

  if v_count >= v_limit then
    raise exception 'Too many submissions. Please try again later.';
  end if;

  insert into public.zw_insert_throttle (bucket, ip) values (tg_table_name, v_ip);
  -- Opportunistic cleanup of old ledger rows (~1% of inserts).
  if random() < 0.01 then
    delete from public.zw_insert_throttle where created_at < now() - interval '2 days';
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.zw_review_language_check()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_text text;
begin
  if tg_op = 'UPDATE'
     and new.title is not distinct from old.title
     and new.body is not distinct from old.body
     and new.nickname is not distinct from old.nickname
     and new.reviewer_name is not distinct from old.reviewer_name then
    return new;
  end if;

  v_text := coalesce(new.title,'') || ' ' || coalesce(new.body,'') || ' '
         || coalesce(new.nickname,'') || ' ' || coalesce(new.reviewer_name,'');

  if exists (
    select 1 from public.zw_banned_words
    where v_text ~* ('\m' || word || '\M')
  ) then
    raise exception 'Your review contains language we can''t publish. Please remove any profanity and try again.';
  end if;

  return new;
end;
$function$
;


-- triggers
CREATE TRIGGER protect_admin_privilege_columns BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION guard_admin_privilege_columns();
CREATE TRIGGER protect_profile_role BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION prevent_profile_role_self_elevation();
CREATE TRIGGER protect_profile_role_self_change BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION prevent_profile_role_self_change();
CREATE TRIGGER reviews_photo_approval_guard BEFORE INSERT OR UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION reviews_guard_photo_approval();
CREATE TRIGGER trg_return_requests_updated_at BEFORE UPDATE ON public.return_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER zw_rate_limit_restock BEFORE INSERT ON public.restock_requests FOR EACH ROW EXECUTE FUNCTION zw_rate_limit('5', '1 hour');
CREATE TRIGGER zw_rate_limit_reviews BEFORE INSERT ON public.reviews FOR EACH ROW EXECUTE FUNCTION zw_rate_limit('5', '1 hour');
CREATE TRIGGER zw_rate_limit_waitlist BEFORE INSERT ON public.waitlist FOR EACH ROW EXECUTE FUNCTION zw_rate_limit('5', '1 hour');
CREATE TRIGGER zw_review_language_check BEFORE INSERT OR UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION zw_review_language_check();

-- row level security
alter table public."abandoned_carts" enable row level security;
alter table public."admin_audit_log" enable row level security;
alter table public."api_key_overrides" enable row level security;
alter table public."api_status_log" enable row level security;
alter table public."bundles" enable row level security;
alter table public."color_variants" enable row level security;
alter table public."disputes" enable row level security;
alter table public."email_log" enable row level security;
alter table public."error_log" enable row level security;
alter table public."favorites" enable row level security;
alter table public."journal_posts" enable row level security;
alter table public."loyalty_ledger" enable row level security;
alter table public."newsletter_subscribers" enable row level security;
alter table public."orders" enable row level security;
alter table public."processed_events" enable row level security;
alter table public."product_images" enable row level security;
alter table public."product_questions" enable row level security;
alter table public."product_sizes" enable row level security;
alter table public."products" enable row level security;
alter table public."profiles" enable row level security;
alter table public."referral_codes" enable row level security;
alter table public."restock_requests" enable row level security;
alter table public."return_requests" enable row level security;
alter table public."reviews" enable row level security;
alter table public."schema_migrations" enable row level security;
alter table public."site_settings" enable row level security;
alter table public."size_charts" enable row level security;
alter table public."tax_exemptions" enable row level security;
alter table public."tax_shadow_log" enable row level security;
alter table public."waitlist" enable row level security;
alter table public."webhook_events" enable row level security;
alter table public."zw_banned_words" enable row level security;
alter table public."zw_insert_throttle" enable row level security;

-- policies
create policy "Admins can insert audit log" on public."admin_audit_log" for insert to "authenticated" with check (((admin_user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = 'admin'::text))))));
create policy "Admins can read audit log" on public."admin_audit_log" for select to "authenticated" using ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = 'admin'::text)))));
create policy "Bundles admin manage" on public."bundles" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Bundles public read active" on public."bundles" for select to "anon", "authenticated" using ((active = true));
create policy "Admin full access" on public."color_variants" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Public read access" on public."color_variants" for select using (true);
create policy "Email log admin read" on public."email_log" for select to "authenticated" using (current_user_is_admin());
create policy "Admin full access" on public."favorites" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Users manage own favorites" on public."favorites" for all using ((auth.uid() = user_id));
create policy "read published posts" on public."journal_posts" for select to "anon", "authenticated" using ((status = 'published'::text));
create policy "Loyalty read own" on public."loyalty_ledger" for select to "authenticated" using (((auth.uid() = user_id) OR current_user_is_admin()));
create policy "Newsletter admin full access" on public."newsletter_subscribers" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Admin full access" on public."orders" for all to "authenticated" using (current_user_can_page('orders'::text)) with check (current_user_can_page('orders'::text));
create policy "Users manage own orders" on public."orders" for all using ((auth.uid() = user_id));
create policy "Admin full access" on public."product_images" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Public read access" on public."product_images" for select using (true);
create policy "ask a question" on public."product_questions" for insert to "anon", "authenticated" with check (((status = 'pending'::text) AND (answer IS NULL) AND ((char_length(question) >= 3) AND (char_length(question) <= 1000))));
create policy "read published questions" on public."product_questions" for select to "anon", "authenticated" using ((status = 'published'::text));
create policy "Admin full access" on public."product_sizes" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Public read access" on public."product_sizes" for select using (true);
create policy "Admin full access" on public."products" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Products delete via endpoint only" on public."products" as restrictive for delete to "authenticated" using (false);
create policy "Public read access" on public."products" for select using (true);
create policy "Admins read profiles" on public."profiles" for select to "authenticated" using (current_user_is_admin());
create policy "Super admins manage profiles" on public."profiles" for all to "authenticated" using (is_super_admin()) with check (is_super_admin());
create policy "Users insert own profile" on public."profiles" for insert to "authenticated" with check ((auth.uid() = id));
create policy "Users read own profile" on public."profiles" for select to "authenticated" using ((auth.uid() = id));
create policy "Users update own profile" on public."profiles" for update to "authenticated" using ((auth.uid() = id)) with check (((auth.uid() = id) AND (role = ( SELECT p.role
   FROM profiles p
  WHERE (p.id = auth.uid()))) AND (NOT (admin_role IS DISTINCT FROM ( SELECT p.admin_role
   FROM profiles p
  WHERE (p.id = auth.uid())))) AND (NOT (admin_permissions IS DISTINCT FROM ( SELECT p.admin_permissions
   FROM profiles p
  WHERE (p.id = auth.uid()))))));
create policy "Referral read own" on public."referral_codes" for select to "authenticated" using (((auth.uid() = user_id) OR current_user_is_admin()));
create policy "Admins delete restock requests" on public."restock_requests" for delete to "authenticated" using (current_user_is_admin());
create policy "Admins manage restock requests" on public."restock_requests" for select to "authenticated" using (current_user_is_admin());
create policy "Public can request restock" on public."restock_requests" for insert to "anon", "authenticated" with check (true);
create policy "Service role full access" on public."return_requests" for all using ((auth.role() = 'service_role'::text)) with check ((auth.role() = 'service_role'::text));
create policy "Users insert own return requests" on public."return_requests" for insert with check ((auth.uid() = user_id));
create policy "Users see own return requests" on public."return_requests" for select using ((auth.uid() = user_id));
create policy "Admin full access" on public."reviews" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Members insert own reviews" on public."reviews" for insert to "authenticated" with check ((auth.uid() = user_id));
create policy "Public read access" on public."reviews" for select using (true);
create policy "Users manage own reviews" on public."reviews" for all using ((auth.uid() = user_id));
create policy "Admin full access" on public."site_settings" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Authz keys delete: super admin only" on public."site_settings" as restrictive for delete to "authenticated" using (((NOT is_authz_settings_key(key)) OR current_user_is_super_admin()));
create policy "Authz keys insert: super admin only" on public."site_settings" as restrictive for insert to "authenticated" with check (((NOT is_authz_settings_key(key)) OR current_user_is_super_admin()));
create policy "Authz keys update: super admin only" on public."site_settings" as restrictive for update to "authenticated" using (((NOT is_authz_settings_key(key)) OR current_user_is_super_admin())) with check (((NOT is_authz_settings_key(key)) OR current_user_is_super_admin()));
create policy "Public read access" on public."site_settings" for select to "anon", "authenticated" using ((key = ANY (ARRAY['shipping_policy'::text, 'announcement_bar'::text, 'brand'::text, 'theme'::text, 'tax_rate_overrides'::text, 'hero'::text, 'fonts'::text, 'legal_policies'::text, 'page_builder_published'::text])));
create policy "Public read content keys" on public."site_settings" for select using ((key = ANY (ARRAY['announcement_bar'::text, 'brand'::text, 'fonts'::text, 'theme'::text, 'header_behavior'::text, 'image_effects'::text, 'nav_menu'::text, 'bag_panel'::text, 'theme_modes'::text, 'icons'::text, 'hero'::text, 'about_page'::text, 'faq'::text, 'technologies'::text, 'legal_policies'::text, 'shipping_policy'::text, 'page_builder_published'::text, 'landing_pages_published'::text, 'collection_page'::text, 'product_card_cta'::text, 'feature_flags'::text, 'fit_finder'::text, 'integrations'::text, 'email_popup'::text, 'tax_rate_overrides'::text])));
create policy "Admin full access" on public."size_charts" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());
create policy "Public read access" on public."size_charts" for select using (true);
create policy "tax exemptions are service-only" on public."tax_exemptions" for all using (false) with check (false);
create policy "shadow log is service-only" on public."tax_shadow_log" for all using (false) with check (false);
create policy "Admins view waitlist" on public."waitlist" for select to "authenticated" using (current_user_is_admin());
create policy "Public can join waitlist" on public."waitlist" for insert with check (true);
create policy "Service role full access" on public."webhook_events" for all using (true) with check (true);
create policy "Admins manage banned words" on public."zw_banned_words" for all to "authenticated" using (current_user_is_admin()) with check (current_user_is_admin());

-- grants
grant delete, insert, references, select, trigger, truncate, update on public."abandoned_carts" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."abandoned_carts" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."abandoned_carts" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."admin_audit_log" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."admin_audit_log" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."admin_audit_log" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."api_key_overrides" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."api_key_overrides" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."api_key_overrides" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."api_status_log" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."api_status_log" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."api_status_log" to "service_role";
grant references, select, trigger, truncate on public."bundles" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."bundles" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."bundles" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."color_variants" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."color_variants" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."color_variants" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."disputes" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."disputes" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."disputes" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."email_log" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."email_log" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."error_log" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."favorites" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."favorites" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."favorites" to "service_role";
grant references, select, trigger, truncate on public."journal_posts" to "anon";
grant references, select, trigger, truncate on public."journal_posts" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."journal_posts" to "service_role";
grant references, select, trigger, truncate on public."loyalty_ledger" to "anon";
grant references, select, trigger, truncate on public."loyalty_ledger" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."loyalty_ledger" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."newsletter_subscribers" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."newsletter_subscribers" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."orders" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."orders" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."orders" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."processed_events" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."processed_events" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."processed_events" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."product_images" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."product_images" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."product_images" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."product_questions" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."product_questions" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."product_questions" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."product_sizes" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."product_sizes" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."product_sizes" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."products" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."products" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."products" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."profiles" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."profiles" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."profiles" to "service_role";
grant references, select, trigger, truncate on public."referral_codes" to "anon";
grant references, select, trigger, truncate on public."referral_codes" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."referral_codes" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."restock_requests" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."restock_requests" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."restock_requests" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."return_requests" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."return_requests" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."return_requests" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."reviews" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."reviews" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."reviews" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."schema_migrations" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."site_settings" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."site_settings" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."site_settings" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."size_charts" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."size_charts" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."size_charts" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."tax_exemptions" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."tax_exemptions" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."tax_exemptions" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."tax_shadow_log" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."tax_shadow_log" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."tax_shadow_log" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."waitlist" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."waitlist" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."waitlist" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."webhook_events" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."webhook_events" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."webhook_events" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."zw_banned_words" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."zw_banned_words" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."zw_banned_words" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."zw_insert_throttle" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."zw_insert_throttle" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."zw_insert_throttle" to "service_role";

-- ============================================================================
-- Record what this snapshot already contains.
--
-- Every migration through HEAD is marked applied because their effects are in
-- the schema above. Without this the runner would try to replay them against a
-- database that already has them — the ALTERs would fail, and a half-applied
-- chain is harder to diagnose than a failed one.
--
-- checksum is 'installed' rather than the file's real hash on purpose: this
-- database did not run that file, it was born with the result. A fabricated
-- checksum would make the migrations panel claim a history that did not happen,
-- which is the same dishonesty the 0000 baseline row was careful to avoid.
--
-- DO NOT ALSO RUN migrations/0001. schema_migrations and apply_migration() are
-- both in the snapshot above — they exist in production, so pg_dump brought
-- them along. This file is complete on its own, and that is the point: one
-- file, run once, with no ordering rule for anyone to get wrong.
-- ============================================================================

insert into public.schema_migrations (version, name, checksum, applied_by)
values
  ('0000', 'baseline_pre_migration_system', 'installed', 'install.sql'),
  ('0001', 'migration_tracking', 'installed', 'install.sql'),
  ('0002', 'public_read_allowlist', 'installed', 'install.sql'),
  ('0003', 'purge_env_only_secrets', 'installed', 'install.sql'),
  ('0004', 'orders_tax_engine', 'installed', 'install.sql'),
  ('0005', 'theme_icon_public_read', 'installed', 'install.sql'),
  ('0006', 'payment_hardening', 'installed', 'install.sql'),
  ('0007', 'decrement_stock_colour_parity', 'installed', 'install.sql'),
  ('0008', 'authz_keys_super_admin_only', 'installed', 'install.sql'),
  ('0009', 'products_delete_via_endpoint_only', 'installed', 'install.sql'),
  ('0010', 'admin_role_is_not_self_service', 'installed', 'install.sql'),
  ('0011', 'tax_categories_exemptions_shadow', 'installed', 'install.sql'),
  ('0012', 'order_actual_shipping_cost', 'installed', 'install.sql'),
  ('0013', 'restock_uses_the_same_row_rule', 'installed', 'install.sql'),
  ('0014', 'api_status_history', 'installed', 'install.sql'),
  ('0015', 'orders_delivered_at', 'installed', 'install.sql'),
  ('0016', 'error_log_retention', 'installed', 'install.sql'),
  ('0017', 'rls_respects_permissions', 'installed', 'install.sql')
on conflict (version) do nothing;
