/* The migration system.
 *
 * The bug being designed against is not "the SQL was wrong" — it is "nobody ran
 * it". The live RLS policy had drifted from every .sql file in the repo,
 * silently disabling two features for weeks. So these tests care as much about
 * the properties that make skipping impossible (ordering, idempotence, drift
 * detection, a destructive file that refuses to run) as about the SQL itself.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const ROOT = path.resolve(__dirname, '..');
let pass = 0, fail = 0;
const ok = (n, c, e) => { if (c) { pass++; console.log('  ✓ ' + n); } else { fail++; console.log('  ✗ ' + n + (e ? '  — ' + e : '')); } };
const codeOnly = (s) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');

const dir = path.join(ROOT, 'migrations');
const files = fs.readdirSync(dir).filter((f) => f.endsWith('.sql')).sort();

console.log('\n  migrations\n');

console.log('  files');
{
  ok(files.length + ' migration file(s) present', files.length >= 2);
  ok('every file is <version>_<name>.sql', files.every((f) => /^\d{4}[_-].+\.sql$/.test(f)), files.join(', '));

  const versions = files.map((f) => f.slice(0, 4));
  ok('versions are unique', new Set(versions).size === versions.length);
  ok('…and sort in the order they must run',
    JSON.stringify(versions) === JSON.stringify([...versions].sort()));
}

console.log('\n  the bundle the runner reads');
{
  const gen = path.join(ROOT, 'functions/api/_migrations.js');
  ok('the generated bundle exists', fs.existsSync(gen));
  const src = fs.readFileSync(gen, 'utf8');
  ok('…and is marked generated so nobody edits it by hand', /GENERATED by scripts\/build-migrations\.js/.test(src));

  const list = JSON.parse(src.slice(src.indexOf('['), src.lastIndexOf(']') + 1));
  ok('bundle has one entry per file', list.length === files.length, list.length + ' vs ' + files.length);

  // The bundle must match the files, or the endpoint applies something other
  // than what is under review.
  let mismatched = [];
  list.forEach((m) => {
    const disk = fs.readFileSync(path.join(dir, m.file), 'utf8').replace(/\r\n/g, '\n');
    if (disk !== m.sql) mismatched.push(m.file + ' (sql)');
    const sum = crypto.createHash('sha256').update(disk).digest('hex').slice(0, 16);
    if (sum !== m.checksum) mismatched.push(m.file + ' (checksum)');
  });
  ok('every bundled migration matches its file exactly', mismatched.length === 0, mismatched.join(', '));
  ok('checksums are computed on normalised line endings, so Windows and CI agree',
    /replace\(\/\\r\\n\/g, '\\n'\)/.test(fs.readFileSync(ROOT + '/scripts/build-migrations.js', 'utf8')));
}

console.log('\n  0001 — the one file a human runs');
{
  const sql = fs.readFileSync(path.join(dir, files[0]), 'utf8');
  ok('creates the tracking table idempotently', /create table if not exists public\.schema_migrations/.test(sql));
  ok('the applier records and executes together, so a failure leaves nothing half-done',
    /execute p_sql;[\s\S]{0,200}insert into public\.schema_migrations/.test(sql));
  ok('an already-applied version is skipped inside the function too',
    /if exists \(select 1 from public\.schema_migrations where version = p_version\)[\s\S]{0,60}return;/.test(sql));
  ok('the applier is security definer', /security definer/.test(sql));
  ok('…and cannot be called by anon or a logged-in user',
    /revoke all on function public\.apply_migration[\s\S]{0,80}from public, anon, authenticated/.test(sql));
  ok('the tracking table is not reachable through the API either',
    /revoke all on public\.schema_migrations from anon, authenticated/.test(sql));
  ok('it records itself so the runner never replays it', /values \('0001'/.test(sql));
  ok('…and baselines the pre-existing hand-run SQL so nothing destructive replays',
    /'0000', 'baseline_pre_migration_system'/.test(sql));
}

console.log('\n  0002 — the drift this system exists to prevent');
{
  const sql = fs.readFileSync(path.join(dir, '0002_public_read_allowlist.sql'), 'utf8');
  const list = (sql.match(/array\[([\s\S]*?)\]/i) || [])[1] || '';
  const keys = (list.match(/'[^']+'/g) || []).map((s) => s.slice(1, -1));

  // The two keys the storefront reads that production was missing.
  ok('fit_finder is restored — Find Your Size was using built-in defaults', keys.includes('fit_finder'));
  ok('integrations is restored — nothing configured there was loading', keys.includes('integrations'));
  // And the draft that should never have been public.
  ok('landing_pages (the draft) is removed', !keys.includes('landing_pages'));
  ok('…while the published landing pages stay readable', keys.includes('landing_pages_published'));
  ok('no secret is in the list',
    !keys.some((k) => /commerce_config|email_settings|_draft$|^page_builder$/.test(k)), keys.join(','));

  // Every key any storefront file reads with the anon key must be in the list,
  // or that feature silently runs on defaults — which is the exact failure.
  const readsAnon = new Set();
  ['fit-finder.js', 'integrations.js', 'announcement-bar.js', 'header-scroll.js',
   'image-effects.js', 'nav-menu.js', 'storefront-features.js'].forEach((f) => {
    const p = path.join(ROOT, f);
    if (!fs.existsSync(p)) return;
    const m = fs.readFileSync(p, 'utf8').match(/key=eq\.([a-z_]+)/g) || [];
    m.forEach((x) => readsAnon.add(x.replace('key=eq.', '')));
  });
  const missing = [...readsAnon].filter((k) => !keys.includes(k));
  ok([...readsAnon].length + ' anon-read keys, all present in the allow-list',
    missing.length === 0, 'missing: ' + missing.join(', '));
}

console.log('\n  the destructive file cannot fire by accident');
{
  const master = fs.readFileSync(ROOT + '/supabase-master-schema.sql', 'utf8');
  ok('it still drops tables (it is the fresh-install path)', /DROP TABLE IF EXISTS/.test(master));
  ok('…but refuses to run when orders already exist',
    /public\.orders[\s\S]{0,200}raise exception/i.test(master));
  ok('…and when products already exist',
    /public\.products[\s\S]{0,200}raise exception/i.test(master));
  ok('the guard runs before the first DROP',
    master.indexOf('raise exception') < master.indexOf('DROP TABLE IF EXISTS'));
  ok('it points at migrations/ for changing an existing database', /migrations\//.test(master));
}

console.log('\n  the runner');
{
  const api = codeOnly(fs.readFileSync(ROOT + '/functions/api/migrate.js', 'utf8'));
  ok('admins only', /prof\.role !== 'admin'/.test(api));
  ok('…and only with apikey_manage', /permsHave\(perms, 'apikey_manage'\)/.test(api));
  ok('applies through the recording function, never raw SQL', /rpc\/apply_migration/.test(api));
  ok('stops at the first failure rather than running the rest',
    /failedAt[\s\S]{0,200}return json/.test(api));
  ok('detects a migration edited after it ran', /appliedChecksum/.test(api));
  ok('tells you to run the bootstrap when the table is missing', /bootstrapped: false/.test(api));

  const admin = fs.readFileSync(ROOT + '/admin.html', 'utf8');
  ok('the panel is in the admin', /id="migrationsPanel"/.test(admin));
  ok('…with an apply button that stays hidden until something is pending',
    /id="migrateApplyBtn"[^>]*display:none/.test(admin));

  const pkg = JSON.parse(fs.readFileSync(ROOT + '/package.json', 'utf8'));
  ok('the bundle is rebuilt on every deploy', /build-migrations/.test(pkg.scripts.postinstall));
}

console.log('\n  ' + pass + ' passed, ' + fail + ' failed\n');
process.exit(fail ? 1 : 0);
