/**
 * Cloudflare Pages Function: /api/shippo-rates
 *
 * Fetches Shippo rates and signs each returned rate so checkout can verify
 * the selected rate was generated by this backend for the submitted address.
 */

const CORS = (env) => ({
  'Access-Control-Allow-Origin': env.SITE_URL || '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Content-Type': 'application/json',
});

// Build a parcel spec for shipping rate calculations.
// actualWeightLb: real packed weight summed from product.shipping_weight_lb (preferred).
// totalItems: used for box dimension scaling in both paths.
// Falls back to the generic 0.5 lb/item estimate when no actual weight is provided.
function buildParcel(totalItems, actualWeightLb) {
  const qty = Math.max(1, Math.round(totalItems));
  const weightLb = actualWeightLb && actualWeightLb > 0
    ? parseFloat(actualWeightLb).toFixed(2)
    : (0.5 + qty * 0.5).toFixed(1);
  const heightIn = qty <= 1 ? '4' : qty <= 3 ? '6' : '8';
  const widthIn  = qty <= 1 ? '10' : qty <= 3 ? '12' : '14';
  return { length: '14', width: widthIn, height: heightIn, distance_unit: 'in', weight: weightLb, mass_unit: 'lb' };
}

function json(body, status, headers) {
  return new Response(JSON.stringify(body), { status, headers });
}

function normalizeAddressPart(value) {
  return String(value || '').trim().toUpperCase();
}

function base64UrlEncode(value) {
  return btoa(value).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function base64UrlEncodeBytes(bytes) {
  let binary = '';
  for (let i = 0; i < bytes.length; i += 1) binary += String.fromCharCode(bytes[i]);
  return base64UrlEncode(binary);
}

async function hmacSha256(message, secret) {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message));
  return base64UrlEncodeBytes(new Uint8Array(signature));
}

async function signRate(rate, address, env, parcel) {
  const secret = env.CHECKOUT_RATE_SECRET || env.STRIPE_SECRET_KEY;
  if (!secret) return '';

  const payload = {
    rateId: rate.objectId,
    amount: String(rate.amount || ''),
    currency: String(rate.currency || 'USD').toUpperCase(),
    provider: rate.provider || '',
    servicelevel: rate.servicelevel || '',
    zip: normalizeAddressPart(address.zip),
    state: normalizeAddressPart(address.state),
    country: normalizeAddressPart(address.country || 'US'),
    parcelWeight: String(parcel?.weight || ''),
    parcelMassUnit: String(parcel?.mass_unit || 'lb'),
    exp: Date.now() + 30 * 60 * 1000,
  };

  const body = base64UrlEncode(JSON.stringify(payload));
  const sig = await hmacSha256(body, secret);
  return `${body}.${sig}`;
}

export async function onRequestOptions({ env }) {
  return new Response(null, { status: 204, headers: CORS(env) });
}

export async function onRequestPost({ request, env }) {
  const headers = CORS(env);

  try {
    if (!env.SHIPPO_API_KEY) {
      return json({ error: 'Shipping rates are not configured.' }, 500, headers);
    }

    const { address, parcel: customParcel, totalItems: itemCount, totalWeightLb } = await request.json();

    if (!address?.zip || !address?.country) {
      return json({ error: 'address.zip and address.country are required' }, 400, headers);
    }

    const parcel = customParcel || buildParcel(itemCount || 1, totalWeightLb);
    const fromAddress = {
      name: env.SHIPPO_FROM_NAME || 'Zuwera',
      street1: env.SHIPPO_FROM_STREET1 || '',
      city: env.SHIPPO_FROM_CITY || '',
      state: env.SHIPPO_FROM_STATE || '',
      zip: env.SHIPPO_FROM_ZIP || '',
      country: env.SHIPPO_FROM_COUNTRY || 'US',
      email: env.SHIPPO_FROM_EMAIL || 'orders@zuwera.store',
    };

    const resp = await fetch('https://api.goshippo.com/shipments/', {
      method: 'POST',
      headers: {
        Authorization: 'ShippoToken ' + env.SHIPPO_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        address_from: fromAddress,
        address_to: {
          name: address.name || 'Customer',
          street1: address.line1 || '',
          city: address.city || '',
          state: address.state || '',
          zip: address.zip,
          country: address.country || 'US',
        },
        parcels: [parcel],
        async: false,
      }),
    });

    if (!resp.ok) {
      const detail = await resp.text();
      console.error('Shippo error:', detail);
      return json({ error: 'Shippo API error' }, 502, headers);
    }

    const data = await resp.json();
    const USPS_PROVIDERS = new Set(['USPS', 'usps']);
    const rates = await Promise.all((data.rates || [])
      .map((r) => ({
        objectId: r.object_id,
        provider: r.provider,
        servicelevel: r.servicelevel?.name,
        amount: r.amount,
        currency: r.currency,
        days: r.estimated_days,
      }))
      .sort((a, b) => {
        const aUsps = USPS_PROVIDERS.has(a.provider) ? 0 : 1;
        const bUsps = USPS_PROVIDERS.has(b.provider) ? 0 : 1;
        if (aUsps !== bUsps) return aUsps - bUsps;
        return parseFloat(a.amount) - parseFloat(b.amount);
      })
      .map(async (rate) => ({
        ...rate,
        rateToken: await signRate(rate, address, env, parcel),
      })));

    return json({ rates }, 200, headers);
  } catch (e) {
    console.error('shippo-rates error:', e);
    return json({ error: e.message }, 500, headers);
  }
}
