/**
 * Cloudflare Pages Function: /api/shippo-rates
 *
 * Fetches Shippo rates and signs each returned rate so checkout can verify
 * the selected rate was generated by this backend for the submitted address.
 */

const CORS = (env) => ({
  'Access-Control-Allow-Origin': env.SITE_URL || '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Content-Type': 'application/json',
});

// Build a parcel spec for shipping rate calculations.
// actualWeightLb: real packed weight summed from product.shipping_weight_lb (preferred).
// totalItems: used for box dimension scaling in both paths.
// Falls back to the generic 0.5 lb/item estimate when no actual weight is provided.
function buildParcel(totalItems, actualWeightLb) {
  const qty = Math.max(1, Math.round(totalItems));
  const weightLb = actualWeightLb && actualWeightLb > 0
    ? parseFloat(actualWeightLb).toFixed(2)
    : (0.5 + qty * 0.5).toFixed(1);
  const heightIn = qty <= 1 ? '4' : qty <= 3 ? '6' : '8';
  const widthIn  = qty <= 1 ? '10' : qty <= 3 ? '12' : '14';
  return { length: '14', width: widthIn, height: heightIn, distance_unit: 'in', weight: weightLb, mass_unit: 'lb' };
}

function json(body, status, headers) {
  return new Response(JSON.stringify(body), { status, headers });
}

function normalizeAddressPart(value) {
  return String(value || '').trim().toUpperCase();
}

function parseQuantity(value) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < 1) return 1;
  return Math.min(parsed, 99);
}

function catalogHeaders(env) {
  const key = env.SUPABASE_SERVICE_ROLE_KEY || env.SUPABASE_SERVICE_KEY || env.SUPABASE_ANON_KEY;
  if (!env.SUPABASE_URL || !key) return null;
  return { apikey: key, Authorization: `Bearer ${key}` };
}

async function fetchCatalogProduct(env, item) {
  const headers = catalogHeaders(env);
  if (!headers) return null;

  const productId = String(item?.productId || item?.id || '').trim();
  const sku = String(item?.sku || '').trim();
  const filters = [];
  if (productId) filters.push(`id=eq.${encodeURIComponent(productId)}`);
  if (sku) filters.push(`sku=eq.${encodeURIComponent(sku)}`);

  for (const filter of filters) {
    const resp = await fetch(`${env.SUPABASE_URL}/rest/v1/products?select=id,sku,shipping_weight_lb&${filter}&limit=1`, { headers });
    if (!resp.ok) continue;
    const rows = await resp.json().catch(() => []);
    if (Array.isArray(rows) && rows[0]) return rows[0];
  }

  return null;
}

async function resolveParcelSummary({ items, itemCount, totalWeightLb, env }) {
  if (!Array.isArray(items) || items.length === 0) {
    const count = Number.parseInt(itemCount, 10) || 1;
    const fallbackWeight = Number.parseFloat(totalWeightLb) || 0;
    return { totalItems: count, totalWeightLb: fallbackWeight };
  }

  let totalItems = 0;
  let totalWeight = 0;
  let resolvedAnyCatalogWeight = false;

  for (const item of items.slice(0, 25)) {
    const quantity = parseQuantity(item?.quantity);
    totalItems += quantity;

    const product = await fetchCatalogProduct(env, item);
    const catalogWeight = Number.parseFloat(product?.shipping_weight_lb);
    const fallbackWeight = Number.parseFloat(item?.weightLb);
    const unitWeight = Number.isFinite(catalogWeight) && catalogWeight > 0
      ? catalogWeight
      : (Number.isFinite(fallbackWeight) && fallbackWeight > 0 ? fallbackWeight : 0.5);

    if (Number.isFinite(catalogWeight) && catalogWeight > 0) resolvedAnyCatalogWeight = true;
    totalWeight += unitWeight * quantity;
  }

  const browserFallbackWeight = Number.parseFloat(totalWeightLb) || 0;
  return {
    totalItems: totalItems || Number.parseInt(itemCount, 10) || 1,
    totalWeightLb: totalWeight > 0 ? totalWeight : browserFallbackWeight,
    source: resolvedAnyCatalogWeight ? 'catalog' : 'cart-fallback',
  };
}

function base64UrlEncode(value) {
  return btoa(value).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function base64UrlEncodeBytes(bytes) {
  let binary = '';
  for (let i = 0; i < bytes.length; i += 1) binary += String.fromCharCode(bytes[i]);
  return base64UrlEncode(binary);
}

async function hmacSha256(message, secret) {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message));
  return base64UrlEncodeBytes(new Uint8Array(signature));
}

async function signRate(rate, address, env, parcel) {
  const secret = env.CHECKOUT_RATE_SECRET || env.STRIPE_SECRET_KEY;
  if (!secret) return '';

  const payload = {
    rateId: rate.objectId,
    amount: String(rate.amount || ''),
    currency: String(rate.currency || 'USD').toUpperCase(),
    provider: rate.provider || '',
    servicelevel: rate.servicelevel || '',
    zip: normalizeAddressPart(address.zip),
    state: normalizeAddressPart(address.state),
    country: normalizeAddressPart(address.country || 'US'),
    parcelWeight: String(parcel?.weight || ''),
    parcelMassUnit: String(parcel?.mass_unit || 'lb'),
    exp: Date.now() + 30 * 60 * 1000,
  };

  const body = base64UrlEncode(JSON.stringify(payload));
  const sig = await hmacSha256(body, secret);
  return `${body}.${sig}`;
}

export async function onRequestOptions({ env }) {
  return new Response(null, { status: 204, headers: CORS(env) });
}

export async function onRequestPost({ request, env }) {
  const headers = CORS(env);

  try {
    if (!env.SHIPPO_API_KEY) {
      return json({ error: 'Shipping rates are not configured.' }, 500, headers);
    }

    const { address, parcel: customParcel, totalItems: itemCount, totalWeightLb, items = [] } = await request.json();

    if (!address?.zip || !address?.country) {
      return json({ error: 'address.zip and address.country are required' }, 400, headers);
    }

    const parcelSummary = await resolveParcelSummary({ items, itemCount, totalWeightLb, env });
    const parcel = customParcel || buildParcel(parcelSummary.totalItems, parcelSummary.totalWeightLb);
    const fromAddress = {
      name: env.SHIPPO_FROM_NAME || 'Zuwera',
      street1: env.SHIPPO_FROM_STREET1 || '',
      city: env.SHIPPO_FROM_CITY || '',
      state: env.SHIPPO_FROM_STATE || '',
      zip: env.SHIPPO_FROM_ZIP || '',
      country: env.SHIPPO_FROM_COUNTRY || 'US',
      email: env.SHIPPO_FROM_EMAIL || 'orders@zuwera.store',
    };

    const resp = await fetch('https://api.goshippo.com/shipments/', {
      method: 'POST',
      headers: {
        Authorization: 'ShippoToken ' + env.SHIPPO_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        address_from: fromAddress,
        address_to: {
          name: address.name || 'Customer',
          street1: address.line1 || '',
          city: address.city || '',
          state: address.state || '',
          zip: address.zip,
          country: address.country || 'US',
        },
        parcels: [parcel],
        async: false,
      }),
    });

    if (!resp.ok) {
      const detail = await resp.text();
      console.error('Shippo error:', detail);
      return json({ error: 'Shippo API error' }, 502, headers);
    }

    const data = await resp.json();
    const USPS_PROVIDERS = new Set(['USPS', 'usps']);
    const rates = await Promise.all((data.rates || [])
      .map((r) => ({
        objectId: r.object_id,
        provider: r.provider,
        servicelevel: r.servicelevel?.name,
        amount: r.amount,
        currency: r.currency,
        days: r.estimated_days,
      }))
      .sort((a, b) => {
        const aUsps = USPS_PROVIDERS.has(a.provider) ? 0 : 1;
        const bUsps = USPS_PROVIDERS.has(b.provider) ? 0 : 1;
        if (aUsps !== bUsps) return aUsps - bUsps;
        return parseFloat(a.amount) - parseFloat(b.amount);
      })
      .map(async (rate) => ({
        ...rate,
        rateToken: await signRate(rate, address, env, parcel),
      })));

    return json({ rates }, 200, headers);
  } catch (e) {
    console.error('shippo-rates error:', e);
    return json({ error: e.message }, 500, headers);
  }
}
