/**
 * Cloudflare Pages Function: /api/shippo-rates
 *
 * Fetches Shippo rates and signs each returned rate so checkout can verify
 * the selected rate was generated by this backend for the submitted address.
 */

import { fetchSiteSettings, resolveSetting } from './_settings.js';
import { veeqoGetRates, veeqoKey } from './_veeqo.js';
import { getShippoMonthlyCount, shippoFreeLimit } from './_shipping-usage.js';

const CORS = (env) => ({
  'Access-Control-Allow-Origin': env.SITE_URL || 'https://zuwera.store',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Content-Type': 'application/json',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
});

// Build a parcel spec for shipping rate calculations.
// actualWeightLb: real packed weight summed from product.shipping_weight_lb (preferred).
// totalItems: used for box dimension scaling in both paths.
// Falls back to the generic 0.5 lb/item estimate when no actual weight is provided.
function buildParcel(totalItems, actualWeightLb) {
  const qty = Math.max(1, Math.round(totalItems));
  const weightLb = actualWeightLb && actualWeightLb > 0
    ? parseFloat(actualWeightLb).toFixed(2)
    : (0.5 + qty * 0.5).toFixed(1);
  const heightIn = qty <= 1 ? '4' : qty <= 3 ? '6' : '8';
  const widthIn  = qty <= 1 ? '10' : qty <= 3 ? '12' : '14';
  return { length: '14', width: widthIn, height: heightIn, distance_unit: 'in', weight: weightLb, mass_unit: 'lb' };
}

function json(body, status, headers) {
  return new Response(JSON.stringify(body), { status, headers });
}

function normalizeAddressPart(value) {
  return String(value || '').trim().toUpperCase();
}

function parseQuantity(value) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < 1) return 1;
  return Math.min(parsed, 99);
}

function catalogHeaders(env) {
  const key = env.SUPABASE_SERVICE_ROLE_KEY || env.SUPABASE_SERVICE_KEY || env.SUPABASE_ANON_KEY;
  if (!env.SUPABASE_URL || !key) return null;
  return { apikey: key, Authorization: `Bearer ${key}` };
}

async function fetchCatalogProduct(env, item) {
  const headers = catalogHeaders(env);
  if (!headers) return null;

  const productId = String(item?.productId || item?.id || '').trim();
  const sku = String(item?.sku || '').trim();
  const filters = [];
  if (productId) filters.push(`id=eq.${encodeURIComponent(productId)}`);
  if (sku) filters.push(`sku=eq.${encodeURIComponent(sku)}`);

  for (const filter of filters) {
    const resp = await fetch(`${env.SUPABASE_URL}/rest/v1/products?select=id,sku,shipping_weight_lb&${filter}&limit=1`, { headers });
    if (!resp.ok) continue;
    const rows = await resp.json().catch(() => []);
    if (Array.isArray(rows) && rows[0]) return rows[0];
  }

  return null;
}

async function resolveParcelSummary({ items, itemCount, totalWeightLb, env }) {
  if (!Array.isArray(items) || items.length === 0) {
    const count = Number.parseInt(itemCount, 10) || 1;
    const fallbackWeight = Number.parseFloat(totalWeightLb) || 0;
    return { totalItems: count, totalWeightLb: fallbackWeight };
  }

  let totalItems = 0;
  let totalWeight = 0;
  let resolvedAnyCatalogWeight = false;

  for (const item of items.slice(0, 25)) {
    const quantity = parseQuantity(item?.quantity);
    totalItems += quantity;

    const product = await fetchCatalogProduct(env, item);
    const catalogWeight = Number.parseFloat(product?.shipping_weight_lb);
    const fallbackWeight = Number.parseFloat(item?.weightLb);
    const unitWeight = Number.isFinite(catalogWeight) && catalogWeight > 0
      ? catalogWeight
      : (Number.isFinite(fallbackWeight) && fallbackWeight > 0 ? fallbackWeight : 0.5);

    if (Number.isFinite(catalogWeight) && catalogWeight > 0) resolvedAnyCatalogWeight = true;
    totalWeight += unitWeight * quantity;
  }

  const browserFallbackWeight = Number.parseFloat(totalWeightLb) || 0;
  return {
    totalItems: totalItems || Number.parseInt(itemCount, 10) || 1,
    totalWeightLb: totalWeight > 0 ? totalWeight : browserFallbackWeight,
    source: resolvedAnyCatalogWeight ? 'catalog' : 'cart-fallback',
  };
}

function base64UrlEncode(value) {
  return btoa(value).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function base64UrlEncodeBytes(bytes) {
  let binary = '';
  for (let i = 0; i < bytes.length; i += 1) binary += String.fromCharCode(bytes[i]);
  return base64UrlEncode(binary);
}

async function hmacSha256(message, secret) {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message));
  return base64UrlEncodeBytes(new Uint8Array(signature));
}

async function signRate(rate, address, env, parcel) {
  const secret = env.CHECKOUT_RATE_SECRET;
  if (!secret) return '';

  const payload = {
    rateId: rate.objectId,
    amount: String(rate.amount || ''),
    currency: String(rate.currency || 'USD').toUpperCase(),
    provider: rate.provider || '',
    servicelevel: rate.servicelevel || '',
    source: rate.source || 'shippo',                  // which API booked this rate
    remoteShipmentId: rate.remoteShipmentId || '',    // Veeqo: needed to buy the label
    zip: normalizeAddressPart(address.zip),
    state: normalizeAddressPart(address.state),
    country: normalizeAddressPart(address.country || 'US'),
    parcelWeight: String(parcel?.weight || ''),
    parcelMassUnit: String(parcel?.mass_unit || 'lb'),
    exp: Date.now() + 30 * 60 * 1000,
  };

  const body = base64UrlEncode(JSON.stringify(payload));
  const sig = await hmacSha256(body, secret);
  return `${body}.${sig}`;
}

const USPS_PROVIDERS = new Set(['USPS', 'usps']);

// Fetch + normalize Shippo rates (no signing yet). Returns [] on any error so a
// Shippo outage/misconfig can't break checkout when Veeqo is available.
async function fetchShippoRates({ env, fromAddress, address, parcel }) {
  try {
    const resp = await fetch('https://api.goshippo.com/shipments/', {
      method: 'POST',
      headers: { Authorization: 'ShippoToken ' + env.SHIPPO_API_KEY, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        address_from: fromAddress,
        address_to: {
          name: address.name || 'Customer',
          street1: address.line1 || '',
          city: address.city || '',
          state: address.state || '',
          zip: address.zip,
          country: address.country || 'US',
        },
        parcels: [parcel],
        async: false,
      }),
    });
    if (!resp.ok) { console.error('Shippo error:', await resp.text().catch(() => '')); return []; }
    const data = await resp.json();
    return (data.rates || []).map((r) => ({
      source: 'shippo',
      objectId: r.object_id,
      provider: r.provider,
      servicelevel: r.servicelevel?.name,
      amount: r.amount,
      currency: r.currency,
      days: r.estimated_days,
    }));
  } catch (e) {
    console.error('Shippo rates fetch failed:', e.message);
    return [];
  }
}

// Services that can't carry apparel. Media Mail / Bound Printed Matter /
// Library Mail are legally restricted to books & printed matter (a clothing
// package can be held, returned, or surcharged) — and since checkout silently
// takes the CHEAPEST USPS rate, Veeqo's $3.95 Bound Printed Matter was about to
// become the store's default shipping method. "Tender to <carrier> only" rates
// require dropping the package at that carrier's facility, which doesn't fit
// the pickup workflow. Tested against the RAW name (cleanServiceName strips
// the "(Tender to FedEx only)" parenthetical this matches on).
const EXCLUDED_SERVICE_RE = /media mail|bound printed|library mail|tender to/i;

// Normalize a service name for display + dedupe. The two providers spell the
// same service differently — "Priority Mail" vs "Priority Mail®", "Ground
// Advantage" vs "Ground Advantage (1 - 70 lb)" — so exact-name dedupe kept
// both and checkout looked glitched with same-price duplicates. Stripping
// marks/parentheticals also makes the webhook's SERVICE_TOKEN_MAP fallback
// (exact names like "Priority Mail") match Veeqo-sourced services.
function cleanServiceName(name) {
  return String(name || '')
    .replace(/[®™]/g, '')
    .replace(/\s*\([^)]*\)/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Drop unusable services, then normalize names (exclusion first — it matches
// text inside the parentheticals that cleaning removes). Exported for tests.
export function filterAndCleanRates(rates) {
  return rates
    .filter((r) => r && !EXCLUDED_SERVICE_RE.test(String(r.servicelevel || '')))
    .map((r) => ({ ...r, servicelevel: cleanServiceName(r.servicelevel) }));
}

// Dedupe rates across providers by carrier+service, keeping the cheapest.
// On an exact price tie, prefer Shippo (per requirement).
function mergeCheapestPerService(rates) {
  const byKey = new Map();
  for (const r of rates) {
    if (!r || !r.amount) continue;
    const key = String(r.provider || '').toUpperCase() + '|' + String(r.servicelevel || '').toUpperCase();
    const cur = byKey.get(key);
    if (!cur) { byKey.set(key, r); continue; }
    const a = parseFloat(r.amount), b = parseFloat(cur.amount);
    if (a < b || (a === b && r.source === 'shippo' && cur.source !== 'shippo')) byKey.set(key, r);
  }
  return [...byKey.values()];
}

// USPS first (primary method), then cheapest.
function sortRates(rates) {
  return rates.sort((a, b) => {
    const aUsps = USPS_PROVIDERS.has(a.provider) ? 0 : 1;
    const bUsps = USPS_PROVIDERS.has(b.provider) ? 0 : 1;
    if (aUsps !== bUsps) return aUsps - bUsps;
    return parseFloat(a.amount) - parseFloat(b.amount);
  });
}

export async function onRequestOptions({ env }) {
  return new Response(null, { status: 204, headers: CORS(env) });
}

export async function onRequestPost({ request, env }) {
  const headers = CORS(env);

  try {
    const { address, parcel: customParcel, totalItems: itemCount, totalWeightLb, items = [], allRates = false } = await request.json();

    if (!address?.zip || !address?.country) {
      return json({ error: 'address.zip and address.country are required' }, 400, headers);
    }

    const parcelSummary = await resolveParcelSummary({ items, itemCount, totalWeightLb, env });
    const parcel = customParcel || buildParcel(parcelSummary.totalItems, parcelSummary.totalWeightLb);

    // Read from-address from Supabase site_settings (admin panel) first, env vars as fallback
    const fromKeys = ['SHIPPO_FROM_NAME','SHIPPO_FROM_STREET1','SHIPPO_FROM_STREET2',
                      'SHIPPO_FROM_CITY','SHIPPO_FROM_STATE','SHIPPO_FROM_ZIP',
                      'SHIPPO_FROM_COUNTRY','SHIPPO_FROM_EMAIL','SHIPPO_FROM_PHONE',
                      'VEEQO_API_KEY','SHIPPO_FREE_LIMIT','shipping_preferred_service'];
    const settingsCache = await fetchSiteSettings(fromKeys, env);
    const rs = (key, fallback = '') => resolveSetting(key, env, settingsCache) || fallback;
    const fromAddress = {
      name:    rs('SHIPPO_FROM_NAME', 'Zuwera'),
      street1: rs('SHIPPO_FROM_STREET1'),
      city:    rs('SHIPPO_FROM_CITY'),
      state:   rs('SHIPPO_FROM_STATE'),
      zip:     rs('SHIPPO_FROM_ZIP'),
      country: rs('SHIPPO_FROM_COUNTRY', 'US'),
      email:   rs('SHIPPO_FROM_EMAIL', 'orders@zuwera.store'),
      phone:   rs('SHIPPO_FROM_PHONE'),
    };

    // ── Provider selection (USPS stays primary via sortRates below) ──────
    // Under the Shippo free-tier limit: query BOTH sources and keep the cheaper
    // rate per service (exact tie -> Shippo). At/over the limit: Veeqo only,
    // falling back to Shippo if Veeqo returns nothing so checkout never loses
    // its rates.
    const shippoCount = await getShippoMonthlyCount(env);
    const limit = shippoFreeLimit(env, settingsCache);
    const veeqoConfigured = !!veeqoKey(env, settingsCache);
    const toAddr = {
      name: address.name, line1: address.line1, city: address.city,
      state: address.state, zip: address.zip, country: address.country || 'US',
    };

    const [shippoRates, veeqoRates] = await Promise.all([
      env.SHIPPO_API_KEY ? fetchShippoRates({ env, fromAddress, address, parcel }) : Promise.resolve([]),
      veeqoConfigured ? veeqoGetRates({ env, from: fromAddress, to: toAddr, parcel, settingsCache }) : Promise.resolve([]),
    ]);

    const pool = (shippoCount < limit)
      ? [...shippoRates, ...veeqoRates]
      : (veeqoRates.length ? veeqoRates : shippoRates);

    if (!pool.length) {
      return json({ error: 'No shipping rates available' }, 502, headers);
    }

    let usable = sortRates(mergeCheapestPerService(filterAndCleanRates(pool)));

    // ── Admin-chosen checkout options ─────────────────────────────────────
    // site_settings `shipping_preferred_service` pins which service(s) the
    // checkout offers:
    //   {services:[{provider,servicelevel},…]}  — one or MORE pinned options
    //   {provider,servicelevel}                 — legacy single-pin shape
    //   {mode:"cheapest"} / absent              — automatic USPS-cheapest
    // Pinned rates come back in the pinned order; `pinned:true` tells checkout
    // to render a picker when there's more than one. If NONE of the pinned
    // services are quoted for this address, fall back to the full sorted list
    // so checkout never loses shipping. `allRates: true` (admin rate-preview)
    // bypasses the pin so every option stays visible.
    let pinned = false;
    if (!allRates) {
      let pref = settingsCache.shipping_preferred_service;
      if (typeof pref === 'string') { try { pref = JSON.parse(pref); } catch (_) { pref = null; } }
      const services = Array.isArray(pref?.services)
        ? pref.services
        : (pref && typeof pref === 'object' && pref.servicelevel ? [pref] : []);
      const matches = services
        .filter((s) => s && s.servicelevel)
        .map((s) => {
          const want = String(s.servicelevel).toUpperCase();
          const wantProv = String(s.provider || '').toUpperCase();
          return usable.find((r) =>
            String(r.servicelevel || '').toUpperCase() === want &&
            (!wantProv || String(r.provider || '').toUpperCase() === wantProv));
        })
        .filter(Boolean);
      if (matches.length) { usable = [...new Set(matches)]; pinned = true; }
    }

    const rates = await Promise.all(
      usable.map(async (rate) => ({
        ...rate,
        rateToken: await signRate(rate, address, env, parcel),
      }))
    );

    // Pre-merge per-provider counts, so a silently dead feed is visible (the
    // dedupe can legitimately drop every rate from one source, making the
    // merged list alone ambiguous about whether both providers answered).
    const sources = { shippo: shippoRates.length, veeqo: veeqoRates.length };

    return json({ rates, sources, pinned }, 200, headers);
  } catch (e) {
    console.error('shippo-rates error:', e);
    return json({ error: e.message }, 500, headers);
  }
}
